require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PartProcessCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # PartProcessCategory. As you add validations to PartProcessCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PartProcessCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all part_process_categories as @part_process_categories" do
      part_process_category = PartProcessCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:part_process_categories).should eq([part_process_category])
    end
  end

  describe "GET show" do
    it "assigns the requested part_process_category as @part_process_category" do
      part_process_category = PartProcessCategory.create! valid_attributes
      get :show, {:id => part_process_category.to_param}, valid_session
      assigns(:part_process_category).should eq(part_process_category)
    end
  end

  describe "GET new" do
    it "assigns a new part_process_category as @part_process_category" do
      get :new, {}, valid_session
      assigns(:part_process_category).should be_a_new(PartProcessCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested part_process_category as @part_process_category" do
      part_process_category = PartProcessCategory.create! valid_attributes
      get :edit, {:id => part_process_category.to_param}, valid_session
      assigns(:part_process_category).should eq(part_process_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PartProcessCategory" do
        expect {
          post :create, {:part_process_category => valid_attributes}, valid_session
        }.to change(PartProcessCategory, :count).by(1)
      end

      it "assigns a newly created part_process_category as @part_process_category" do
        post :create, {:part_process_category => valid_attributes}, valid_session
        assigns(:part_process_category).should be_a(PartProcessCategory)
        assigns(:part_process_category).should be_persisted
      end

      it "redirects to the created part_process_category" do
        post :create, {:part_process_category => valid_attributes}, valid_session
        response.should redirect_to(PartProcessCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved part_process_category as @part_process_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcessCategory.any_instance.stub(:save).and_return(false)
        post :create, {:part_process_category => {}}, valid_session
        assigns(:part_process_category).should be_a_new(PartProcessCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcessCategory.any_instance.stub(:save).and_return(false)
        post :create, {:part_process_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested part_process_category" do
        part_process_category = PartProcessCategory.create! valid_attributes
        # Assuming there are no other part_process_categories in the database, this
        # specifies that the PartProcessCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PartProcessCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => part_process_category.to_param, :part_process_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested part_process_category as @part_process_category" do
        part_process_category = PartProcessCategory.create! valid_attributes
        put :update, {:id => part_process_category.to_param, :part_process_category => valid_attributes}, valid_session
        assigns(:part_process_category).should eq(part_process_category)
      end

      it "redirects to the part_process_category" do
        part_process_category = PartProcessCategory.create! valid_attributes
        put :update, {:id => part_process_category.to_param, :part_process_category => valid_attributes}, valid_session
        response.should redirect_to(part_process_category)
      end
    end

    describe "with invalid params" do
      it "assigns the part_process_category as @part_process_category" do
        part_process_category = PartProcessCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcessCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => part_process_category.to_param, :part_process_category => {}}, valid_session
        assigns(:part_process_category).should eq(part_process_category)
      end

      it "re-renders the 'edit' template" do
        part_process_category = PartProcessCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcessCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => part_process_category.to_param, :part_process_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested part_process_category" do
      part_process_category = PartProcessCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => part_process_category.to_param}, valid_session
      }.to change(PartProcessCategory, :count).by(-1)
    end

    it "redirects to the part_process_categories list" do
      part_process_category = PartProcessCategory.create! valid_attributes
      delete :destroy, {:id => part_process_category.to_param}, valid_session
      response.should redirect_to(part_process_categories_url)
    end
  end

end
