require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PartProcessesController do

  # This should return the minimal set of attributes required to create a valid
  # PartProcess. As you add validations to PartProcess, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PartProcessesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all part_processes as @part_processes" do
      part_process = PartProcess.create! valid_attributes
      get :index, {}, valid_session
      assigns(:part_processes).should eq([part_process])
    end
  end

  describe "GET show" do
    it "assigns the requested part_process as @part_process" do
      part_process = PartProcess.create! valid_attributes
      get :show, {:id => part_process.to_param}, valid_session
      assigns(:part_process).should eq(part_process)
    end
  end

  describe "GET new" do
    it "assigns a new part_process as @part_process" do
      get :new, {}, valid_session
      assigns(:part_process).should be_a_new(PartProcess)
    end
  end

  describe "GET edit" do
    it "assigns the requested part_process as @part_process" do
      part_process = PartProcess.create! valid_attributes
      get :edit, {:id => part_process.to_param}, valid_session
      assigns(:part_process).should eq(part_process)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PartProcess" do
        expect {
          post :create, {:part_process => valid_attributes}, valid_session
        }.to change(PartProcess, :count).by(1)
      end

      it "assigns a newly created part_process as @part_process" do
        post :create, {:part_process => valid_attributes}, valid_session
        assigns(:part_process).should be_a(PartProcess)
        assigns(:part_process).should be_persisted
      end

      it "redirects to the created part_process" do
        post :create, {:part_process => valid_attributes}, valid_session
        response.should redirect_to(PartProcess.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved part_process as @part_process" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcess.any_instance.stub(:save).and_return(false)
        post :create, {:part_process => {}}, valid_session
        assigns(:part_process).should be_a_new(PartProcess)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcess.any_instance.stub(:save).and_return(false)
        post :create, {:part_process => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested part_process" do
        part_process = PartProcess.create! valid_attributes
        # Assuming there are no other part_processes in the database, this
        # specifies that the PartProcess created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PartProcess.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => part_process.to_param, :part_process => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested part_process as @part_process" do
        part_process = PartProcess.create! valid_attributes
        put :update, {:id => part_process.to_param, :part_process => valid_attributes}, valid_session
        assigns(:part_process).should eq(part_process)
      end

      it "redirects to the part_process" do
        part_process = PartProcess.create! valid_attributes
        put :update, {:id => part_process.to_param, :part_process => valid_attributes}, valid_session
        response.should redirect_to(part_process)
      end
    end

    describe "with invalid params" do
      it "assigns the part_process as @part_process" do
        part_process = PartProcess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcess.any_instance.stub(:save).and_return(false)
        put :update, {:id => part_process.to_param, :part_process => {}}, valid_session
        assigns(:part_process).should eq(part_process)
      end

      it "re-renders the 'edit' template" do
        part_process = PartProcess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PartProcess.any_instance.stub(:save).and_return(false)
        put :update, {:id => part_process.to_param, :part_process => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested part_process" do
      part_process = PartProcess.create! valid_attributes
      expect {
        delete :destroy, {:id => part_process.to_param}, valid_session
      }.to change(PartProcess, :count).by(-1)
    end

    it "redirects to the part_processes list" do
      part_process = PartProcess.create! valid_attributes
      delete :destroy, {:id => part_process.to_param}, valid_session
      response.should redirect_to(part_processes_url)
    end
  end

end
