require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SampleLinesController do

  # This should return the minimal set of attributes required to create a valid
  # SampleLine. As you add validations to SampleLine, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SampleLinesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sample_lines as @sample_lines" do
      sample_line = SampleLine.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sample_lines).should eq([sample_line])
    end
  end

  describe "GET show" do
    it "assigns the requested sample_line as @sample_line" do
      sample_line = SampleLine.create! valid_attributes
      get :show, {:id => sample_line.to_param}, valid_session
      assigns(:sample_line).should eq(sample_line)
    end
  end

  describe "GET new" do
    it "assigns a new sample_line as @sample_line" do
      get :new, {}, valid_session
      assigns(:sample_line).should be_a_new(SampleLine)
    end
  end

  describe "GET edit" do
    it "assigns the requested sample_line as @sample_line" do
      sample_line = SampleLine.create! valid_attributes
      get :edit, {:id => sample_line.to_param}, valid_session
      assigns(:sample_line).should eq(sample_line)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SampleLine" do
        expect {
          post :create, {:sample_line => valid_attributes}, valid_session
        }.to change(SampleLine, :count).by(1)
      end

      it "assigns a newly created sample_line as @sample_line" do
        post :create, {:sample_line => valid_attributes}, valid_session
        assigns(:sample_line).should be_a(SampleLine)
        assigns(:sample_line).should be_persisted
      end

      it "redirects to the created sample_line" do
        post :create, {:sample_line => valid_attributes}, valid_session
        response.should redirect_to(SampleLine.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sample_line as @sample_line" do
        # Trigger the behavior that occurs when invalid params are submitted
        SampleLine.any_instance.stub(:save).and_return(false)
        post :create, {:sample_line => {}}, valid_session
        assigns(:sample_line).should be_a_new(SampleLine)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SampleLine.any_instance.stub(:save).and_return(false)
        post :create, {:sample_line => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sample_line" do
        sample_line = SampleLine.create! valid_attributes
        # Assuming there are no other sample_lines in the database, this
        # specifies that the SampleLine created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SampleLine.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sample_line.to_param, :sample_line => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sample_line as @sample_line" do
        sample_line = SampleLine.create! valid_attributes
        put :update, {:id => sample_line.to_param, :sample_line => valid_attributes}, valid_session
        assigns(:sample_line).should eq(sample_line)
      end

      it "redirects to the sample_line" do
        sample_line = SampleLine.create! valid_attributes
        put :update, {:id => sample_line.to_param, :sample_line => valid_attributes}, valid_session
        response.should redirect_to(sample_line)
      end
    end

    describe "with invalid params" do
      it "assigns the sample_line as @sample_line" do
        sample_line = SampleLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SampleLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => sample_line.to_param, :sample_line => {}}, valid_session
        assigns(:sample_line).should eq(sample_line)
      end

      it "re-renders the 'edit' template" do
        sample_line = SampleLine.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SampleLine.any_instance.stub(:save).and_return(false)
        put :update, {:id => sample_line.to_param, :sample_line => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sample_line" do
      sample_line = SampleLine.create! valid_attributes
      expect {
        delete :destroy, {:id => sample_line.to_param}, valid_session
      }.to change(SampleLine, :count).by(-1)
    end

    it "redirects to the sample_lines list" do
      sample_line = SampleLine.create! valid_attributes
      delete :destroy, {:id => sample_line.to_param}, valid_session
      response.should redirect_to(sample_lines_url)
    end
  end

end
